//
//  File.swift
//  Maksmart
//
//  Created by Esra ÖZTÜRK on 3.11.2019.
//  Copyright © 2019 Esra ÖZTÜRK. All rights reserved.
//

import Foundation
public enum ApiResponseError: String, Decodable {
    case MISSING_REQUEST_PARAMETER = "MISSING_REQUEST_PARAMETER"
    case UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    case INVALID_METHOD_ARGUMENT = "INVALID_METHOD_ARGUMENT"
    case CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION"
    case HTTP_MESSAGE_NOT_READABLE = "HTTP_MESSAGE_NOT_READABLE"
    case HTTP_MESSAGE_NOT_WRITABLE = "HTTP_MESSAGE_NOT_WRITABLE"
    case DATA_INTEGRITY_VIOLATION = "DATA_INTEGRITY_VIOLATION"
    case METHOD_ARGUMENT_TYPE_MISMATCH = "METHOD_ARGUMENT_TYPE_MISMATCH"
    case ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    case PROPERTY_NOT_FOUND = "PROPERTY_NOT_FOUND"
    case FILE_SIZE_TOO_BIG = "FILE_SIZE_TOO_BIG"
    case REQUESTED_MEDIA_NOT_FOUND = "REQUESTED_MEDIA_NOT_FOUND"
    case BAD_CREDENTIALS = "BAD_CREDENTIALS"
    case INVALID_ENTITY_OPERATION = "INVALID_ENTITY_OPERATION"
    case INVALID_EXCEL_FORMAT_ = "INVALID_EXCEL_FORMAT_"
    case PASSWORD_RESET_TOKEN_REQUEST_TIME_TOO_EARLY = "PASSWORD_RESET_TOKEN_REQUEST_TIME_TOO_EARLY"
    case PASSWORD_RESET_TOKEN_TIME_OUT = "PASSWORD_RESET_TOKEN_TIME_OUT"
    case SUPREMA_SDK_ERROR = "SUPREMA_SDK_ERROR"
    case NO_REFRESH_TOKEN = "NO_REFRESH_TOKEN"
    case DATA_CONFLICT_EXCEPTION = "DATA_CONFLICT_EXCEPTION"
    case USER_NOT_FOUND = "USER_NOT_FOUND"
    case INVALID_PASSWORD_RESET_TOKEN = "INVALID_PASSWORD_RESET_TOKEN"
}
